import type { GameDataType } from "./types"

export const gameData: GameDataType = {
  questions: [
    {
      id: 1,
      text: "Principal Parker tells you: 'Buddy the Bulldog mascot costume disappeared yesterday after school. When was the last time anyone saw Buddy?'",
      options: [
        "During morning announcements",
        "At lunch time",
        "During the pep rally after school",
        "At the basketball practice last night",
      ],
      correctAnswer: "During the pep rally after school",
      hint: "Think about when most students would have seen the mascot together.",
      character: "principal",
      location: "Principal's Office",
      evidence: "Missing Time: After the pep rally",
    },
    {
      id: 2,
      text: "You check the gym where the pep rally was held. The janitor, Mr. Jenkins, is cleaning. What should you ask him first?",
      options: [
        "Did you take the mascot costume?",
        "Did you see anyone suspicious after the pep rally?",
        "Do you know who wore the mascot costume?",
        "What time did you lock the gym?",
      ],
      correctAnswer: "What time did you lock the gym?",
      hint: "You need to establish a timeline for when the costume could have been taken.",
      character: "janitor",
      location: "School Gym",
      evidence: "Gym Timeline: Locked at 6:30 PM",
    },
    {
      id: 3,
      text: "Mr. Jenkins says: 'I locked the gym at 6:30 PM. The costume was still in the storage closet at 6:15 PM when I checked.' What does this tell you?",
      options: [
        "Mr. Jenkins is lying",
        "The costume was taken between 6:15 and 6:30 PM",
        "The costume was taken after 6:30 PM by someone with a key",
        "The costume was never in the gym",
      ],
      correctAnswer: "The costume was taken between 6:15 and 6:30 PM",
      hint: "Consider the timeline Mr. Jenkins provided.",
      character: "janitor",
      location: "School Gym",
    },
    {
      id: 4,
      text: "You examine the storage closet. What's the most important thing to look for?",
      options: ["Fingerprints on the door", "Signs of forced entry", "The mascot costume", "Other missing items"],
      correctAnswer: "Signs of forced entry",
      hint: "This will tell you if someone broke in or had access.",
      location: "Storage Closet",
      evidence: "Storage Closet: No signs of forced entry",
    },
    {
      id: 5,
      text: "There are no signs of forced entry on the storage closet door. What does this suggest?",
      options: [
        "The janitor took the costume",
        "Someone picked the lock",
        "The costume was never there",
        "Someone with a key or access took the costume",
      ],
      correctAnswer: "Someone with a key or access took the costume",
      hint: "Think about who would have legitimate access to the storage area.",
      location: "Storage Closet",
    },
    {
      id: 6,
      text: "You ask Ms. Thompson, the cheer coach, who has access to the storage closet. She says:",
      options: [
        "Only the janitor and herself",
        "All teachers and staff",
        "The janitor, coaches, and student team captains",
        "Anyone who asks for permission",
      ],
      correctAnswer: "The janitor, coaches, and student team captains",
      hint: "Think about who would need regular access to sports equipment.",
      character: "coach",
      location: "Teacher's Lounge",
      evidence: "Access List: Janitor, coaches, team captains",
    },
    {
      id: 7,
      text: "You find a small blue thread near where the costume was stored. What might this tell you?",
      options: [
        "The mascot costume was blue",
        "The janitor has blue uniforms",
        "It could be from the thief's clothing",
        "It's not related to the case",
      ],
      correctAnswer: "It could be from the thief's clothing",
      hint: "Consider what this physical evidence might reveal about the culprit.",
      location: "Storage Closet",
      evidence: "Physical Clue: Blue thread",
    },
    {
      id: 8,
      text: "You check the sign-out sheet for the storage closet key. Who signed it out yesterday afternoon?",
      options: [
        "No one signed it out",
        "Ms. Thompson (cheer coach)",
        "Jake Miller (basketball team captain)",
        "Emma Chen (drama club president)",
      ],
      correctAnswer: "Emma Chen (drama club president)",
      hint: "Look for someone who doesn't typically need access to the sports equipment.",
      location: "Main Office",
      evidence: "Sign-out Sheet: Emma Chen",
    },
    {
      id: 9,
      text: "You find Emma Chen rehearsing in the auditorium. When asked about the key, she says:",
      options: [
        "She needed props for the school play",
        "She never signed out any key",
        "She was looking for her lost backpack",
        "Ms. Thompson asked her to get some pom-poms",
      ],
      correctAnswer: "She needed props for the school play",
      hint: "Consider which answer sounds most plausible for a drama club president.",
      character: "emma",
      location: "School Auditorium",
    },
    {
      id: 10,
      text: "Emma mentions she saw someone else near the storage closet. Who did she see?",
      options: [
        "Mr. Jenkins the janitor",
        "Tyler Wong from the science club",
        "Coach Davis from the rival school",
        "Jake Miller, the basketball captain",
      ],
      correctAnswer: "Tyler Wong from the science club",
      hint: "Think about who wouldn't normally have a reason to be near the storage closet.",
      character: "emma",
      location: "School Auditorium",
      evidence: "Witness Account: Tyler near closet",
    },
    {
      id: 11,
      text: "You find Tyler in the science lab. When you ask why he was near the storage closet, he says:",
      options: [
        "He was never near the storage closet",
        "He was looking for the basketball coach",
        "He was taking measurements for a science project",
        "He was helping Emma get props",
      ],
      correctAnswer: "He was taking measurements for a science project",
      hint: "Consider what a science club member might be doing.",
      character: "tyler",
      location: "Science Lab",
    },
    {
      id: 12,
      text: "Tyler's project is about sound acoustics. What's suspicious about this?",
      options: [
        "Nothing, it sounds legitimate",
        "The storage closet is too small for acoustic testing",
        "The gym would be a better place for acoustic testing",
        "Science projects aren't allowed in the gym area",
      ],
      correctAnswer: "The gym would be a better place for acoustic testing",
      hint: "Think about where you would test sound in a school.",
      character: "tyler",
      location: "Science Lab",
    },
    {
      id: 13,
      text: "You notice Tyler is wearing a blue sweater with a loose thread. What should you do?",
      options: [
        "Accuse him of stealing the mascot",
        "Ask him about his sweater casually",
        "Grab the thread to compare it",
        "Ignore it and continue questioning",
      ],
      correctAnswer: "Ask him about his sweater casually",
      hint: "You need more information, but don't want to make him defensive.",
      character: "tyler",
      location: "Science Lab",
      evidence: "Blue Sweater: Matches the thread",
    },
    {
      id: 14,
      text: "Tyler seems nervous when you mention his sweater. He says he's had it for years. What's your next question?",
      options: [
        "Why are you lying about the sweater?",
        "Do you know anything about the missing mascot costume?",
        "Were you at the pep rally yesterday?",
        "Can I see your science project notes?",
      ],
      correctAnswer: "Were you at the pep rally yesterday?",
      hint: "You need to establish if he had opportunity and motive.",
      character: "tyler",
      location: "Science Lab",
    },
    {
      id: 15,
      text: "Tyler admits he was at the pep rally but left early. Why is this important?",
      options: [
        "It proves he's innocent",
        "It means he missed seeing the mascot",
        "It gives him an alibi",
        "It puts him at the scene around the time of the theft",
      ],
      correctAnswer: "It puts him at the scene around the time of the theft",
      hint: "Consider the timeline of events and when the mascot went missing.",
      character: "tyler",
      location: "Science Lab",
    },
    {
      id: 16,
      text: "You ask Tyler why he left the pep rally early. He says:",
      options: [
        "He had to finish homework",
        "He wasn't feeling well",
        "He doesn't like sports events",
        "The rival school's mascot was making fun of our team",
      ],
      correctAnswer: "The rival school's mascot was making fun of our team",
      hint: "Look for a motive related to school pride or rivalry.",
      character: "tyler",
      location: "Science Lab",
      evidence: "Motive: Rivalry with other school",
    },
    {
      id: 17,
      text: "You learn that the championship game is against Westfield High, our biggest rival. What's significant about this?",
      options: [
        "Nothing, it's just a coincidence",
        "The mascot might have been stolen as a prank by Westfield",
        "Tyler might have taken it to prevent embarrassment",
        "The janitor probably hid it to avoid cleaning it",
      ],
      correctAnswer: "Tyler might have taken it to prevent embarrassment",
      hint: "Consider how the timing of the theft relates to the upcoming game.",
      location: "Principal's Office",
      evidence: "Context: Championship game against rivals",
    },
    {
      id: 18,
      text: "You check Tyler's locker with permission from Principal Parker. What do you hope to find?",
      options: [
        "The entire mascot costume",
        "Tyler's diary admitting the theft",
        "Evidence linking Tyler to the costume",
        "Nothing, Tyler is innocent",
      ],
      correctAnswer: "Evidence linking Tyler to the costume",
      hint: "Be realistic about what might be in the locker.",
      location: "School Hallway",
    },
    {
      id: 19,
      text: "In Tyler's locker, you find a small piece of fake fur that matches Buddy's costume. What does this suggest?",
      options: [
        "Tyler has his own mascot costume",
        "Tyler likely took the mascot costume",
        "Someone planted evidence in Tyler's locker",
        "The fur is from something else",
      ],
      correctAnswer: "Tyler likely took the mascot costume",
      hint: "Consider the most logical explanation for this evidence.",
      location: "Tyler's Locker",
      evidence: "Physical Evidence: Matching fur in locker",
    },
    {
      id: 20,
      text: "You confront Tyler with the evidence. How should you approach him?",
      options: [
        "Accuse him angrily of ruining the big game",
        "Tell him he's expelled and in big trouble",
        "Ask him to explain the evidence calmly",
        "Call the police immediately",
      ],
      correctAnswer: "Ask him to explain the evidence calmly",
      hint: "You want to get the truth and recover the mascot, not just punish someone.",
      character: "tyler",
      location: "Principal's Office",
    },
    {
      id: 21,
      text: "Tyler breaks down and admits he took the mascot costume. What was his reason?",
      options: [
        "He wanted to wear it himself at the game",
        "He was paid by the rival school to take it",
        "He wanted to modify it to look better for our team",
        "He was tired of our mascot being mocked by the rival school",
      ],
      correctAnswer: "He was tired of our mascot being mocked by the rival school",
      hint: "Remember his earlier comment about the rival mascot.",
      character: "tyler",
      location: "Principal's Office",
      evidence: "Confession: Tyler took the mascot",
    },
    {
      id: 22,
      text: "Tyler explains he was planning to return the costume before the game. Where did he hide it?",
      options: [
        "In his bedroom at home",
        "In the school's basement",
        "In the science lab storage room",
        "In the woods behind the school",
      ],
      correctAnswer: "In the science lab storage room",
      hint: "Think about where Tyler would have easy access.",
      character: "tyler",
      location: "Principal's Office",
    },
    {
      id: 23,
      text: "You find the mascot costume in the science lab storage room. What has Tyler done to it?",
      options: [
        "Damaged it beyond repair",
        "Added cool lights and effects to it",
        "Nothing, it's exactly the same",
        "Painted it different colors",
      ],
      correctAnswer: "Added cool lights and effects to it",
      hint: "Consider Tyler's skills as a science club member.",
      location: "Science Lab Storage",
      evidence: "Modified Costume: Added special effects",
    },
    {
      id: 24,
      text: "The costume now has LED lights that flash in school colors and a small speaker that plays the school fight song. How should this be handled?",
      options: [
        "Tyler should be suspended for stealing",
        "The modifications should be removed",
        "Tyler should be praised for the improvements",
        "Principal Parker should decide what to do",
      ],
      correctAnswer: "Principal Parker should decide what to do",
      hint: "This is ultimately a school discipline matter.",
      location: "Principal's Office",
    },
    {
      id: 25,
      text: "Principal Parker is impressed with the modifications but concerned about the theft. What's a fair resolution?",
      options: [
        "Expel Tyler immediately",
        "Give Tyler detention but use his modified costume",
        "Remove the modifications and pretend nothing happened",
        "Ban Tyler from attending the championship game",
      ],
      correctAnswer: "Give Tyler detention but use his modified costume",
      hint: "Consider both consequences and recognition of good intentions.",
      character: "principal",
      location: "Principal's Office",
    },
  ],
  characters: {
    principal: {
      name: "Principal Parker",
      role: "School Principal",
      description:
        "A fair but strict principal who cares deeply about school spirit and the upcoming championship game.",
      notes: "Very concerned about finding the mascot before the big game. Seems genuinely worried rather than angry.",
      quotes: [
        "This mascot has been part of our school tradition for 25 years!",
        "The championship game is this Friday - we need Buddy back by then!",
      ],
    },
    janitor: {
      name: "Mr. Jenkins",
      role: "School Janitor",
      description:
        "Has worked at the school for 15 years. Knows every corner of the building and is very detail-oriented.",
      notes: "Very precise about his schedule and routines. Seems trustworthy and observant.",
      quotes: [
        "I always lock up at exactly 6:30 PM, never a minute earlier or later.",
        "I've seen all kinds of things go missing over the years, but never the mascot!",
      ],
    },
    coach: {
      name: "Ms. Thompson",
      role: "Cheer Coach",
      description:
        "Energetic and passionate about school spirit. Organizes all the pep rallies and trains the student who wears the mascot costume.",
      notes: "Very upset about the missing mascot. Has been making posters and announcements about it.",
      quotes: [
        "Whoever took Buddy has really hurt our school spirit!",
        "The storage closet is usually very secure - I don't understand how this happened.",
      ],
    },
    emma: {
      name: "Emma Chen",
      role: "Drama Club President",
      description:
        "A talented and ambitious junior who takes her role in the drama club very seriously. Known for attention to detail.",
      notes: "Seems honest about borrowing the key, but might know more than she initially shared.",
      quotes: [
        "I only needed some props for our play - I returned the key right away!",
        "The science club kids are always hanging around places they shouldn't be.",
      ],
    },
    tyler: {
      name: "Tyler Wong",
      role: "Science Club Member",
      description:
        "A quiet sophomore who excels in science and engineering. Known for creative inventions and projects.",
      notes: "Becomes nervous when questioned directly. The blue thread matches his sweater.",
      quotes: [
        "I was just doing research for my project, that's all.",
        "Our school deserves better than being laughed at by Westfield High.",
      ],
    },
    all: {
      name: "All Characters",
      role: "Case Suspects",
      description: "View all the people involved in the case of the missing mascot.",
    },
  },
  evidence: {
    "Missing Time: After the pep rally": {
      description: "The mascot costume was last seen during the pep rally after school.",
      relevance: "Establishes the beginning of our timeline.",
    },
    "Gym Timeline: Locked at 6:30 PM": {
      description: "Mr. Jenkins confirmed he locked the gym at 6:30 PM, and the costume was still there at 6:15 PM.",
      relevance: "Narrows down the time of theft to a 15-minute window.",
    },
    "Storage Closet: No signs of forced entry": {
      description: "The storage closet where the mascot was kept shows no signs of forced entry.",
      relevance: "Suggests the thief had a key or proper access.",
    },
    "Access List: Janitor, coaches, team captains": {
      description: "The storage closet is accessible to the janitor, coaches, and student team captains.",
      relevance: "Identifies who normally has legitimate access.",
    },
    "Physical Clue: Blue thread": {
      description: "A small blue thread was found near where the mascot costume was stored.",
      relevance: "Could be from the thief's clothing.",
    },
    "Sign-out Sheet: Emma Chen": {
      description: "Emma Chen, the drama club president, signed out the storage closet key yesterday afternoon.",
      relevance: "Identifies someone with access during the critical time period.",
    },
    "Witness Account: Tyler near closet": {
      description: "Emma saw Tyler Wong from the science club near the storage closet.",
      relevance: "Places a potential suspect at the scene.",
    },
    "Blue Sweater: Matches the thread": {
      description: "Tyler is wearing a blue sweater with a loose thread that matches what was found.",
      relevance: "Physical evidence connecting Tyler to the scene.",
    },
    "Motive: Rivalry with other school": {
      description: "Tyler was upset that the rival school's mascot was making fun of our team.",
      relevance: "Establishes a potential motive for taking the mascot.",
    },
    "Context: Championship game against rivals": {
      description: "The championship game against our biggest rival, Westfield High, is coming up.",
      relevance: "Provides context for why the mascot is important and why someone might take it.",
    },
    "Physical Evidence: Matching fur in locker": {
      description: "A piece of fake fur matching the mascot costume was found in Tyler's locker.",
      relevance: "Strong evidence linking Tyler to the missing costume.",
    },
    "Confession: Tyler took the mascot": {
      description: "Tyler admitted to taking the mascot costume because he was tired of it being mocked.",
      relevance: "Confirms Tyler as the culprit and explains his motive.",
    },
    "Modified Costume: Added special effects": {
      description: "Tyler added LED lights and a speaker to the mascot costume to make it more impressive.",
      relevance: "Shows Tyler's intentions were to improve the mascot, not harm the school.",
    },
  },
  locations: {
    "Principal's Office": {
      name: "Principal's Office",
      description: "Where Principal Parker manages the school. Contains important records and the master key cabinet.",
    },
    "School Gym": {
      name: "School Gym",
      description: "Where the pep rally was held. This is where Buddy the Bulldog was last seen.",
    },
    "Storage Closet": {
      name: "Storage Closet",
      description: "Where sports equipment and the mascot costume are kept. Access is restricted.",
    },
    "Teacher's Lounge": {
      name: "Teacher's Lounge",
      description: "Where teachers and staff take breaks and have meetings.",
    },
    "Main Office": {
      name: "Main Office",
      description: "The school's administrative center where sign-out sheets and records are kept.",
    },
    "School Auditorium": {
      name: "School Auditorium",
      description: "Where the drama club rehearses for school plays and performances.",
    },
    "Science Lab": {
      name: "Science Lab",
      description: "Where science classes and club activities take place. Contains various equipment.",
    },
    "Science Lab Storage": {
      name: "Science Lab Storage",
      description: "A small room connected to the science lab where supplies and projects are stored.",
    },
    "School Hallway": {
      name: "School Hallway",
      description: "The main corridor with student lockers lining both sides.",
    },
    "Tyler's Locker": {
      name: "Tyler's Locker",
      description: "Tyler Wong's personal locker in the school hallway.",
    },
  },
  conclusion:
    "The case of the missing mascot is solved! Tyler Wong from the science club took Buddy the Bulldog because he was tired of our mascot being mocked by the rival school. Instead of damaging it, he actually improved it by adding LED lights that flash in school colors and a speaker that plays our fight song! Principal Parker decided that while Tyler would serve detention for taking school property without permission, his modified costume would be used at the championship game. The improved Buddy was a hit with everyone, and our team won the championship! Tyler's school spirit, though misguided, ultimately helped bring the school together.",
}
